# Generated by Django 5.2.5 on 2025-09-11 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parlor.staff'),
        ),
    ]
