# Generated by Django 5.2.5 on 2025-09-11 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlor', '0005_alter_booking_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='staff',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parlor.staff'),
        ),
    ]
