# Generated by Django 5.2.5 on 2025-09-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlor', '0008_alter_booking_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(max_length=20),
        ),
    ]
