# Generated by Django 5.2.5 on 2025-09-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlor', '0010_alter_staff_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='staff',
        ),
        migrations.AddField(
            model_name='booking',
            name='staff',
            field=models.ManyToManyField(to='parlor.staff'),
        ),
    ]
