# Generated by Django 5.2.5 on 2025-09-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlor', '0013_remove_booking_staff_booking_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(max_length=40),
        ),
    ]
