# Generated by Django 5.2.5 on 2025-09-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlor', '0014_alter_staff_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
