# Generated by Django 5.2.5 on 2025-09-16 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlor', '0015_alter_order_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='spa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orderItem', to='parlor.spa'),
        ),
    ]
