# Generated by Django 5.2.5 on 2025-09-18 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlor', '0016_bookingitem_spa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('plan', models.CharField(choices=[('essential', 'Essential - KSh 1,500/month'), ('standard', 'standard - KSh 1,800/month'), ('premium', 'premium - KSh 2,500/month')], default='standard', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
