# Generated by Django 5.2.5 on 2025-09-21 16:11

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlor', '0017_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='product_img/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_img',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='service_img/'),
        ),
        migrations.AlterField(
            model_name='spa',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='spa_logos/'),
        ),
        migrations.AlterField(
            model_name='spadashboard',
            name='dashboard_img1',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='dashboard_img1/'),
        ),
        migrations.AlterField(
            model_name='spadashboard',
            name='dashboard_img2',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='dashboard_img2/'),
        ),
        migrations.AlterField(
            model_name='spadashboard',
            name='dashboard_img3',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='dashboard_img3/'),
        ),
        migrations.AlterField(
            model_name='spadashboard',
            name='dashboard_img4',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='dashboard_img4/'),
        ),
        migrations.AlterField(
            model_name='spadashboard',
            name='dashboard_img5',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='dashboard_img5/'),
        ),
        migrations.AlterField(
            model_name='spadashboard',
            name='dashboard_img6',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='dashboard_img6/'),
        ),
        migrations.AlterField(
            model_name='spadashboard',
            name='dashboard_img7',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='dashboard_img7/'),
        ),
        migrations.AlterField(
            model_name='spadashboard',
            name='dashboard_img8',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='dashboard_img8/'),
        ),
        migrations.AlterField(
            model_name='spahome_welcome',
            name='start_img',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='home_img/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='staff_profile/'),
        ),
    ]
