# Generated by Django 5.2.5 on 2025-09-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlor', '0017_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='plan',
            field=models.CharField(choices=[('free trail', 'free trial - 0.00/month'), ('standard', 'standard - KSh 1,500/month'), ('premium', 'premium - KSh 1,800/month')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
