# Generated by Django 5.2.5 on 2025-09-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlor', '0018_alter_request_plan_alter_staff_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='staff/'),
        ),
    ]
