# Generated by Django 5.2.5 on 2025-09-21 13:47

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlor', '0019_alter_staff_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='staff/'),
        ),
    ]
